import "./globals.css";
import { ReactNode } from "react";

export const metadata = {
  title: "tsutsumi-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja" data-theme="dark">
      <body>{children}</body>
    </html>
  );
}
